- Add logging usage, sample
catchfashion/corgi-template pull request #4
Opened 2020-07-15 09:07 UTC by deerFried

## What is this?
[Asana](https://app.asana.com/0/1128532709616896/1184444980146273)

## Changes
- Update logging usage, sample code

2020-07-16 01:38 UTC, breath103 requested changes

2020-07-16 01:38 UTC, breath103 commented on readme.md
> +npm run deploy:stage
줄바꿈 다 날아갔는데?

2020-07-16 01:40 UTC, deerFried commented on readme.md
> +npm run deploy:stage
아 이거 제 vscode에서 파일 저장하면 뒤에 의미없는 공백들 전부 날려서 그런거같아요;

2020-07-21 05:45 UTC, breath103 requested changes

2020-07-21 05:45 UTC, breath103 commented on serverless.yml
> +  cron:
?? cron은 어떻게 넣으라는건지 설명 없는데요?

2020-07-21 05:49 UTC, deerFried commented on serverless.yml
> +  cron:
로그를 어떻게 적용시키는지요?

2020-08-05 09:57 UTC, breath103 approved these changes

2020-08-05 09:57 UTC, merged